version: "3.2"

services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: migrator:build
    depends_on:
      - postgres
      - mariadb
    tty: true

  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: migrator
    ports:
      - 2345:5432

  mariadb:
    image: mariadb:10.4.3
    restart: always
    environment:
      MYSQL_DATABASE: migrator
      MYSQL_ROOT_PASSWORD: mariadb
    ports:
      - 6033:3306
